import { db } from "@/db";
import { searchHistory } from "@/db/schema";
import { auth } from "@/lib/auth";
import { validateSearchHistory, validateSearchHistoryId } from "@/lib/validation";
import { eq, desc } from "drizzle-orm";
import { headers } from "next/headers";
import { NextResponse } from "next/server"; export async function GET() { const session = await auth.api.getSession({ headers: await headers(), }); if (!session) { return NextResponse.json({ error: "Tidak terotorisasi" }, { status: 401 }); } try { const items = await db.query.searchHistory.findMany({ where: eq(searchHistory.userId, session.user.id), orderBy: [desc(searchHistory.createdAt)], limit: 10, }); return NextResponse.json(items); } catch (error) { console.error("Error fetching search history:", error); return NextResponse.json({ error: "Internal Server Error" }, { status: 500 }); }
} export async function POST(request) { const session = await auth.api.getSession({ headers: await headers(), }); if (!session) { return NextResponse.json({ error: "Tidak terotorisasi" }, { status: 401 }); } try { const body = await request.json(); const result = validateSearchHistory(body); if (!result.valid) { return NextResponse.json({ error: "Validation failed", errors: result.errors }, { status: 400 }); } const { data } = result; await db.insert(searchHistory).values({ id: crypto.randomUUID(), userId: session.user.id, query: data.query, lat: data.lat, lng: data.lng, }); const allItems = await db.query.searchHistory.findMany({ where: eq(searchHistory.userId, session.user.id), orderBy: [desc(searchHistory.createdAt)], columns: { id: true }, }); if (allItems.length > 50) { const excess = allItems.slice(50); for (const item of excess) { await db.delete(searchHistory).where(eq(searchHistory.id, item.id)); } } return NextResponse.json({ success: true }); } catch (error) { console.error("Error saving search history:", error); return NextResponse.json({ error: "Internal Server Error" }, { status: 500 }); }
} export async function DELETE(request) { const session = await auth.api.getSession({ headers: await headers(), }); if (!session) { return NextResponse.json({ error: "Tidak terotorisasi" }, { status: 401 }); } try { const { searchParams } = new URL(request.url); const id = searchParams.get("id"); const idResult = validateSearchHistoryId(id); if (!idResult.valid) { return NextResponse.json({ error: idResult.message }, { status: 400 }); } await db.delete(searchHistory).where(eq(searchHistory.id, id)); return NextResponse.json({ success: true }); } catch (error) { console.error("Error deleting search history:", error); return NextResponse.json({ error: "Internal Server Error" }, { status: 500 }); }
}