import { db } from "@/db";
import { savedLocations } from "@/db/schema";
import { auth } from "@/lib/auth";
import { validateLocation, validateLocationId } from "@/lib/validation";
import { eq, and } from "drizzle-orm";
import { headers } from "next/headers";
import { NextResponse } from "next/server"; // ponytail: no pagination — all locations returned at once. Add ?limit=20&offset=0 cursor-based pagination when users exceed 100 saved locations.
export async function GET() { const session = await auth.api.getSession({ headers: await headers(), }); if (!session) { return NextResponse.json({ error: "Tidak terotorisasi" }, { status: 401 }); } try { const list = await db.query.savedLocations.findMany({ where: eq(savedLocations.userId, session.user.id), orderBy: (loc, { desc }) =>[desc(loc.createdAt)], }); return NextResponse.json(list); } catch (error) { console.error("Error fetching locations:", error); return NextResponse.json({ error: "Internal Server Error" }, { status: 500 }); }
} export async function POST(request) { const session = await auth.api.getSession({ headers: await headers(), }); if (!session) { return NextResponse.json({ error: "Tidak terotorisasi" }, { status: 401 }); } try { const body = await request.json(); const result = validateLocation(body); if (!result.valid) { return NextResponse.json({ error: "Validation failed", errors: result.errors }, { status: 400 }); } const { data } = result; const id = crypto.randomUUID(); const success = await db.transaction(async (tx) => { const list = await tx.query.savedLocations.findMany({ where: eq(savedLocations.userId, session.user.id), }); if (list.length >= 20) { return false; } await tx.insert(savedLocations).values({ id, userId: session.user.id, name: data.name, lat: data.lat, lng: data.lng, zoom: data.zoom, }); return true; }); if (!success) { return NextResponse.json({ error: "Limit bookmark tercapai" }, { status: 400 }); } return NextResponse.json({ success: true, id }); } catch (error) { console.error("Error creating location:", error); return NextResponse.json({ error: "Internal Server Error" }, { status: 500 }); }
} export async function DELETE(request) { const session = await auth.api.getSession({ headers: await headers(), }); if (!session) { return NextResponse.json({ error: "Tidak terotorisasi" }, { status: 401 }); } try { const { searchParams } = new URL(request.url); const id = searchParams.get("id"); if (!id) { return NextResponse.json({ error: "Missing ID parameter" }, { status: 400 }); } const idCheck = validateLocationId(id); if (!idCheck.valid) { return NextResponse.json({ error: idCheck.message }, { status: 400 }); } await db.delete(savedLocations) .where(and( eq(savedLocations.id, id), eq(savedLocations.userId, session.user.id) )); return NextResponse.json({ success: true }); } catch (error) { console.error("Error deleting location:", error); return NextResponse.json({ error: "Internal Server Error" }, { status: 500 }); }
}
