import { pgTable, text, timestamp, boolean, integer, doublePrecision, real, jsonb, index } from 'drizzle-orm/pg-core'; // ponytail: only PK/unique indexes — no explicit indexes on user_id, created_at. Add index() calls for userPreferences.user_id, savedLocations.user_id + created_at when query performance at scale becomes a concern. // Better-Auth User Table
export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull(), image: text('image'), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull(),
}); // Better-Auth Session Table
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull().references(() =>user.id, { onDelete: 'cascade' }),
}); // Better-Auth Account Table
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull().references(() =>user.id, { onDelete: 'cascade' }), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull(),
}); // Better-Auth Verification Table
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt'), updatedAt: timestamp('updatedAt'),
}); // Custom User Preferences Table
export const userPreferences = pgTable('user_preferences', { id: text('id').primaryKey(), userId: text('user_id').notNull().unique().references(() =>user.id, { onDelete: 'cascade' }), centerLat: doublePrecision('center_lat').default(-2.5489).notNull(), centerLng: doublePrecision('center_lng').default(118.0149).notNull(), zoom: integer('zoom').default(5).notNull(), opacity: real('opacity').default(0.7).notNull(), colorScheme: integer('color_scheme').default(1).notNull(), mapStyle: text('map_style').default('dark').notNull(), alertConfig: jsonb('alert_config').default({ highWind: 40, heavyRain: 8, poorAQI: 100 }).notNull(), updatedAt: timestamp('updated_at').defaultNow().notNull(),
}); // Custom Search History Table
export const searchHistory = pgTable('search_history', { id: text('id').primaryKey(), userId: text('user_id').notNull().references(() =>user.id, { onDelete: 'cascade' }), query: text('query').notNull(), lat: doublePrecision('lat').notNull(), lng: doublePrecision('lng').notNull(), createdAt: timestamp('created_at').defaultNow().notNull(),
}); // Custom Saved Locations Table
export const savedLocations = pgTable('saved_locations', { id: text('id').primaryKey(), userId: text('user_id').notNull().references(() =>user.id, { onDelete: 'cascade' }), name: text('name').notNull(), lat: doublePrecision('lat').notNull(), lng: doublePrecision('lng').notNull(), zoom: integer('zoom').default(10).notNull(), createdAt: timestamp('created_at').defaultNow().notNull(),
});
